app.service('Classes', function() {

	var classes = {
		"Nohr_Prince": {
			"key": "Nohr_Prince",
			"name": "Nohr Prince",
			"promotesTo": ["Nohr_Noble", "Hoshido_Noble"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Nobility", "Dragon_Fang"],
			"bases": {"HP": 17, "Str": 7, "Mag": 3, "Skl": 4, "Spd": 5, "Lck": 2, "Def": 5, "Res": 2},
			"growths": {"HP": 15, "Str": 15, "Mag": 10, "Skl": 10, "Spd": 10, "Lck": 10, "Def": 10, "Res": 5},
			"maxStats": {"HP": 40, "Str": 23, "Mag": 17, "Skl": 19, "Spd": 21, "Lck": 22, "Def": 21, "Res": 19},
			"weaponRanks": {"Sword": "B", "Stone": "B"},
			"gender": "M",
			"genderEquivalent": "Nohr_Princess",
			"parallel": null,
			"sealAccess": false,
			"inheritAccess": true,
		},

		"Nohr_Princess": {
			"key": "Nohr_Princess",
			"name": "Nohr Princess",
			"promotesTo": ["Nohr_Noble", "Hoshido_Noble"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Nobility", "Dragon_Fang"],
			"bases": {"HP": 17, "Str": 7, "Mag": 3, "Skl": 4, "Spd": 5, "Lck": 2, "Def": 5, "Res": 2},
			"growths": {"HP": 15, "Str": 15, "Mag": 10, "Skl": 10, "Spd": 10, "Lck": 10, "Def": 10, "Res": 5},
			"maxStats": {"HP": 40, "Str": 23, "Mag": 17, "Skl": 19, "Spd": 21, "Lck": 22, "Def": 21, "Res": 19},
			"weaponRanks": {"Sword": "B", "Stone": "B"},
			"gender": "F",
			"genderEquivalent": "Nohr_Prince",
			"parallel": null,
			"sealAccess": false,
			"inheritAccess": true,
		},

		"Hoshido_Noble": {
			"key": "Hoshido_Noble",
			"name": "Hoshido Noble",
			"promotesTo": null,
			"promotesFrom": ["Nohr_Prince", "Nohr_Princess"],
			"classTier": "tier2",
			"skills": ["Dragon_Ward", "Hoshidan_Unity"],
			"bases": {"HP": 19, "Str": 10, "Mag": 4, "Skl": 5, "Spd": 6, "Lck": 4, "Def": 7, "Res": 3},
			"growths": {"HP": 15, "Str": 15, "Mag": 10, "Skl": 10, "Spd": 10, "Lck": 10, "Def": 15, "Res": 0},
			"maxStats": {"HP": 60, "Str": 34, "Mag": 28, "Skl": 29, "Spd": 30, "Lck": 33, "Def": 31, "Res": 28},
			"weaponRanks": {"Sword": "A", "Staff": "B", "Stone": "A"},
			"sealAccess": false,
			"inheritAccess": true,
		},

		"Nohr_Noble": {
			"key": "Nohr_Noble",
			"name": "Nohr Noble",
			"promotesTo": null,
			"promotesFrom": ["Nohr_Prince", "Nohr_Princess"],
			"classTier": "tier2",
			"skills": ["Draconic_Hex", "Nohrian_Trust"],
			"bases": {"HP": 18, "Str": 8, "Mag": 6, "Skl": 4, "Spd": 7, "Lck": 2, "Def": 6, "Res": 6},
			"growths": {"HP": 15, "Str": 10, "Mag": 15, "Skl": 5, "Spd": 15, "Lck": 5, "Def": 5, "Res": 15},
			"maxStats": {"HP": 60, "Str": 32, "Mag": 31, "Skl": 28, "Spd": 32, "Lck": 27, "Def": 29, "Res": 32},
			"weaponRanks": {"Sword": "A", "Tome": "B", "Stone": "A"},
			"sealAccess": false,
			"inheritAccess": true,
		},	

		"Samurai": {
			"key": "Samurai",
			"name": "Samurai",
			"promotesTo": ["Swordmaster", "Master_of_Arms"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Duelists_Blow", "Vantage"],
			"bases": {"HP": 17, "Str": 4, "Mag": 0, "Skl": 5, "Spd": 8, "Lck": 3, "Def": 3, "Res": 3},
			"growths": {"HP": 10, "Str": 10, "Mag": 0, "Skl": 15, "Spd": 20, "Lck": 15, "Def": 0, "Res": 10},
			"maxStats": {"HP": 40, "Str": 20, "Mag": 16, "Skl": 23, "Spd": 25, "Lck": 24, "Def": 18, "Res": 20},
			"weaponRanks": {"Sword": "B"},
			"parallel": "Mercenary",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Swordmaster": {
			"key": "Swordmaster",
			"name": "Swordmaster",
			"promotesTo": null,
			"promotesFrom": ["Samurai"],
			"classTier": "tier2",
			"skills": ["Astra", "Swordfaire"],
			"bases": {"HP": 18, "Str": 6, "Mag": 2, "Skl": 7, "Spd": 11, "Lck": 4, "Def": 5, "Res": 5},
			"growths": {"HP": 10, "Str": 10, "Mag": 5, "Skl": 15, "Spd": 20, "Lck": 15, "Def": 0, "Res": 10},
			"maxStats": {"HP": 55, "Str": 30, "Mag": 28, "Skl": 32, "Spd": 35, "Lck": 33, "Def": 27, "Res": 31},
			"weaponRanks": {"Sword": "S"},
			"bonus": {"Crit": 10, "Avo": 10},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Master_of_Arms": {
			"key": "Master_of_Arms",
			"name": "Master of Arms",
			"promotesTo": null,
			"promotesFrom": ["Samurai", "Villager"],
			"classTier": "tier2",
			"skills": ["Seal_Strength", "Life_or_Death"],
			"bases": {"HP": 20, "Str": 8, "Mag": 0, "Skl": 6, "Spd": 9, "Lck": 3, "Def": 7, "Res": 3},
			"growths": {"HP": 20, "Str": 15, "Mag": 0, "Skl": 10, "Spd": 10, "Lck": 10, "Def": 10, "Res": 0},
			"maxStats": {"HP": 65, "Str": 33, "Mag": 25, "Skl": 30, "Spd": 30, "Lck": 31, "Def": 31, "Res": 28},
			"weaponRanks": {"Sword": "A", "Lance": "B", "Axe": "B"},
			"sealAccess": true,
			"inheritAccess": true,
		},	

		"Villager": {
			"key": "Villager",
			"name": "Villager",
			"promotesTo": ["Master_of_Arms", "Merchant"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Aptitude", "Underdog"],
			"bases": {"HP": 17, "Str": 5, "Mag": 0, "Skl": 4, "Spd": 5, "Lck": 3, "Def": 4, "Res": 0},
			"growths": {"HP": 10, "Str": 10, "Mag": 0, "Skl": 10, "Spd": 10, "Lck": 20, "Def": 10, "Res": 0},
			"maxStats": {"HP": 35, "Str": 19, "Mag": 15, "Skl": 19, "Spd": 19, "Lck": 22, "Def": 18, "Res": 15},
			"weaponRanks": {"Lance": "C"},
			"parallel": "Apothecary",
			"sealAccess": false,
			"inheritAccess": false,
		},

		"Merchant": {
			"key": "Merchant",
			"name": "Merchant",
			"promotesTo": null,
			"promotesFrom": ["Apothecary", "Villager"],
			"classTier": "tier2",
			"skills": ["Profiteer", "Spendthrift"],
			"bases": {"HP": 20, "Str": 8, "Mag": 0, "Skl": 6, "Spd": 5, "Lck": 4, "Def": 8, "Res": 5},
			"growths": {"HP": 20, "Str": 20, "Mag": 0, "Skl": 10, "Spd": 5, "Lck": 15, "Def": 10, "Res": 5},
			"maxStats": {"HP": 65, "Str": 33, "Mag": 25, "Skl": 29, "Spd": 28, "Lck": 32, "Def": 33, "Res": 30},
			"weaponRanks": {"Lance": "B", "Bow": "A"},
			"sealAccess": true,
			"inheritAccess": true,
		},	

		"Apothecary": {
			"key": "Apothecary",
			"name": "Apothecary",
			"promotesTo": ["Merchant", "Mechanist"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Potent_Potion", "Quick_Salve"],
			"bases": {"HP": 18, "Str": 6, "Mag": 0, "Skl": 4, "Spd": 4, "Lck": 2, "Def": 6, "Res": 2},
			"growths": {"HP": 20, "Str": 20, "Mag": 0, "Skl": 10, "Spd": 10, "Lck": 5, "Def": 10, "Res": 5},
			"maxStats": {"HP": 45, "Str": 24, "Mag": 15, "Skl": 19, "Spd": 19, "Lck": 21, "Def": 23, "Res": 20},
			"weaponRanks": {"Bow": "B"},
			"parallel": null,
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Oni_Savage": {
			"key": "Oni_Savage",
			"name": "Oni Savage",
			"promotesTo": ["Oni_Chieftain", "Blacksmith"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Seal_Resistance", "Shove"],
			"bases": {"HP": 18, "Str": 6, "Mag": 1, "Skl": 2, "Spd": 5, "Lck": 0, "Def": 7, "Res": 1},
			"growths": {"HP": 20, "Str": 20, "Mag": 10, "Skl": 0, "Spd": 10, "Lck": 0, "Def": 20, "Res": 0},
			"maxStats": {"HP": 45, "Str": 24, "Mag": 19, "Skl": 16, "Spd": 20, "Lck": 17, "Def": 23, "Res": 18},
			"weaponRanks": {"Axe": "B"},
			"parallel": "Fighter",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Oni_Chieftain": {
			"key": "Oni_Chieftain",
			"name": "Oni Chieftain",
			"promotesTo": null,
			"promotesFrom": ["Oni_Savage"],
			"classTier": "tier2",
			"skills": ["Death_Blow", "Counter"],
			"bases": {"HP": 19, "Str": 9, "Mag": 5, "Skl": 2, "Spd": 7, "Lck": 0, "Def": 10, "Res": 5},
			"growths": {"HP": 10, "Str": 20, "Mag": 15, "Skl": 0, "Spd": 10, "Lck": 0, "Def": 20, "Res": 5},
			"maxStats": {"HP": 60, "Str": 34, "Mag": 28, "Skl": 25, "Spd": 30, "Lck": 25, "Def": 36, "Res": 31},
			"weaponRanks": {"Axe": "A", "Tome": "B"},
			"sealAccess": true,
			"inheritAccess": true,
		},	

		"Blacksmith": {
			"key": "Blacksmith",
			"name": "Blacksmith",
			"promotesTo": null,
			"promotesFrom": ["Oni_Savage"],
			"classTier": "tier2",
			"skills": ["Salvage_Blow", "Lancebreaker"],
			"bases": {"HP": 21, "Str": 8, "Mag": 0, "Skl": 9, "Spd": 8, "Lck": 3, "Def": 8, "Res": 2},
			"growths": {"HP": 20, "Str": 15, "Mag": 0, "Skl": 15, "Spd": 10, "Lck": 5, "Def": 15, "Res": 0},
			"maxStats": {"HP": 65, "Str": 33, "Mag": 25, "Skl": 32, "Spd": 31, "Lck": 30, "Def": 32, "Res": 27},
			"weaponRanks": {"Sword": "B", "Axe": "B"},
			"sealAccess": true,
			"inheritAccess": true,
		},	

		"Spear_Fighter": {
			"key": "Spear_Fighter",
			"name": "Spear Fighter",
			"promotesTo": ["Spear_Master", "Basara"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Seal_Defense", "Swap"],
			"bases": {"HP": 17, "Str": 6, "Mag": 0, "Skl": 6, "Spd": 6, "Lck": 2, "Def": 5, "Res": 2},
			"growths": {"HP": 15, "Str": 15, "Mag": 0, "Skl": 15, "Spd": 15, "Lck": 5, "Def": 10, "Res": 5},
			"maxStats": {"HP": 40, "Str": 22, "Mag": 15, "Skl": 23, "Spd": 22, "Lck": 21, "Def": 22, "Res": 21},
			"weaponRanks": {"Lance": "B"},
			"parallel": "Knight",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Spear_Master": {
			"key": "Spear_Master",
			"name": "Spear Master",
			"promotesTo": null,
			"promotesFrom": ["Spear_Fighter"],
			"classTier": "tier2",
			"skills": ["Seal_Speed", "Lancefaire"],
			"bases": {"HP": 18, "Str": 9, "Mag": 0, "Skl": 8, "Spd": 8, "Lck": 3, "Def": 7, "Res": 3},		
			"growths": {"HP": 15, "Str": 15, "Mag": 0, "Skl": 15, "Spd": 15, "Lck": 5, "Def": 10, "Res": 5},
			"maxStats": {"HP": 60, "Str": 34, "Mag": 25, "Skl": 33, "Spd": 32, "Lck": 29, "Def": 30, "Res": 29},
			"weaponRanks": {"Lance": "S"},
			"bonus": {"Crit": 10, "Ddg": 10},
			"sealAccess": true,
			"inheritAccess": true,
		},	

		"Basara": {
			"key": "Basara",
			"name": "Basara",
			"promotesTo": null,
			"promotesFrom": ["Spear_Fighter", "Diviner"],
			"classTier": "tier2",
			"skills": ["Rend_Heaven", "Quixotic"],
			"bases": {"HP": 20, "Str": 7, "Mag": 5, "Skl": 7, "Spd": 7, "Lck": 5, "Def": 7, "Res": 6},		
			"growths": {"HP": 20, "Str": 10, "Mag": 10, "Skl": 10, "Spd": 10, "Lck": 15, "Def": 5, "Res": 10},
			"maxStats": {"HP": 65, "Str": 31, "Mag": 30, "Skl": 30, "Spd": 31, "Lck": 35, "Def": 30, "Res": 32},
			"weaponRanks": {"Lance": "A", "Tome": "B"},
			"sealAccess": true,
			"inheritAccess": true,
		},	

		"Diviner": {
			"key": "Diviner",
			"name": "Diviner",
			"promotesTo": ["Onmyoji", "Basara"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Magic+2", "Future_Sight"],
			"bases": {"HP": 15, "Str": 0, "Mag": 4, "Skl": 5, "Spd": 6, "Lck": 1, "Def": 1, "Res": 3},
			"growths": {"HP": 0, "Str": 5, "Mag": 15, "Skl": 10, "Spd": 10, "Lck": 5, "Def": 0, "Res": 10},
			"maxStats": {"HP": 35, "Str": 17, "Mag": 22, "Skl": 20, "Spd": 23, "Lck": 19, "Def": 16, "Res": 20},
			"weaponRanks": {"Tome": "B"},
			"parallel": "Dark_Mage",
			"sealAccess": true,
			"inheritAccess": true,
		},	

		"Onmyoji": {
			"key": "Onmyoji",
			"name": "Onmyoji",
			"promotesTo": null,
			"promotesFrom": ["Diviner", "Monk", "Shrine_Maiden"],
			"classTier": "tier2",
			"skills": ["Rally_Magic", "Tomefaire"],
			"bases": {"HP": 16, "Str": 0, "Mag": 7, "Skl": 6, "Spd": 7, "Lck": 2, "Def": 3, "Res": 6},		
			"growths": {"HP": 0, "Str": 0, "Mag": 20, "Skl": 10, "Spd": 15, "Lck": 0, "Def": 0, "Res": 15},
			"maxStats": {"HP": 45, "Str": 25, "Mag": 33, "Skl": 31, "Spd": 32, "Lck": 27, "Def": 25, "Res": 31},
			"weaponRanks": {"Tome": "A", "Staff": "B"},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Monk": {
			"key": "Monk",
			"name": "Monk",
			"promotesTo": ["Great_Master", "Onmyoji"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Miracle", "Rally_Luck"],
			"bases": {"HP": 16, "Str": 0, "Mag": 3, "Skl": 5, "Spd": 5, "Lck": 4, "Def": 2, "Res": 5},
			"growths": {"HP": 0, "Str": 5, "Mag": 10, "Skl": 10, "Spd": 15, "Lck": 15, "Def": 0, "Res": 20},
			"maxStats": {"HP": 35, "Str": 18, "Mag": 21, "Skl": 20, "Spd": 22, "Lck": 23, "Def": 17, "Res": 24},
			"weaponRanks": {"Staff": "B"},
			"bonus": {"Ddg": 10},
			"gender": "M",
			"genderEquivalent": "Shrine_Maiden",
			"parallel": null,
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Shrine_Maiden": {
			"key": "Shrine_Maiden",
			"name": "Shrine Maiden",
			"promotesTo": ["Priestess", "Onmyoji"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Miracle", "Rally_Luck"],
			"bases": {"HP": 16, "Str": 0, "Mag": 3, "Skl": 5, "Spd": 5, "Lck": 4, "Def": 2, "Res": 5},
			"growths": {"HP": 0, "Str": 5, "Mag": 10, "Skl": 10, "Spd": 15, "Lck": 15, "Def": 0, "Res": 20},
			"maxStats": {"HP": 35, "Str": 18, "Mag": 21, "Skl": 20, "Spd": 22, "Lck": 23, "Def": 17, "Res": 24},
			"weaponRanks": {"Staff": "B"},
			"bonus": {"Ddg": 10},
			"gender": "F",
			"genderEquivalent": "Monk",
			"parallel": null,
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Great_Master": {
			"key": "Great_Master",
			"name": "Great Master",
			"promotesTo": null,
			"promotesFrom": ["Monk"],
			"classTier": "tier2",
			"skills": ["Renewal", "Countermagic"],
			"bases": {"HP": 19, "Str": 8, "Mag": 6, "Skl": 6, "Spd": 8, "Lck": 5, "Def": 6, "Res": 7},		
			"growths": {"HP": 10, "Str": 15, "Mag": 5, "Skl": 5, "Spd": 15, "Lck": 15, "Def": 10, "Res": 10},
			"maxStats": {"HP": 55, "Str": 32, "Mag": 30, "Skl": 31, "Spd": 33, "Lck": 32, "Def": 28, "Res": 32},
			"weaponRanks": {"Lance": "B", "Staff": "A"},
			"gender": "M",
			"genderEquivalent": "Priestess",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Priestess": {
			"key": "Priestess",
			"name": "Priestess",
			"promotesTo": null,
			"promotesFrom": ["Shrine_Maiden"],
			"classTier": "tier2",
			"skills": ["Renewal", "Countermagic"],
			"bases": {"HP": 19, "Str": 6, "Mag": 7, "Skl": 6, "Spd": 9, "Lck": 5, "Def": 5, "Res": 8},		
			"growths": {"HP": 10, "Str": 10, "Mag": 10, "Skl": 5, "Spd": 15, "Lck": 15, "Def": 0, "Res": 20},
			"maxStats": {"HP": 50, "Str": 29, "Mag": 32, "Skl": 30, "Spd": 33, "Lck": 34, "Def": 26, "Res": 34},
			"weaponRanks": {"Bow": "B", "Staff": "A"},
			"gender": "F",
			"genderEquivalent": "Great_Master",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Sky_Knight": {
			"key": "Sky_Knight",
			"name": "Sky Knight",
			"promotesTo": ["Falcon_Knight", "Kinshi_Knight"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Darting_Blow", "Camaraderie"],
			"bases": {"HP": 16, "Str": 3, "Mag": 0, "Skl": 5, "Spd": 7, "Lck": 4, "Def": 2, "Res": 6},
			"growths": {"HP": 0, "Str": 10, "Mag": 0, "Skl": 10, "Spd": 15, "Lck": 20, "Def": 0, "Res": 20},
			"maxStats": {"HP": 35, "Str": 19, "Mag": 16, "Skl": 21, "Spd": 23, "Lck": 25, "Def": 18, "Res": 25},
			"weaponRanks": {"Lance": "B"},
			"parallel": "Wyvern_Rider",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Falcon_Knight": {
			"key": "Falcon_Knight",
			"name": "Falcon Knight",
			"promotesTo": null,
			"promotesFrom": ["Sky_Knight"],
			"classTier": "tier2",
			"skills": ["Rally_Speed", "Warding_Blow"],
			"bases": {"HP": 18, "Str": 5, "Mag": 4, "Skl": 6, "Spd": 10, "Lck": 5, "Def": 5, "Res": 9},		
			"growths": {"HP": 0, "Str": 10, "Mag": 10, "Skl": 10, "Spd": 15, "Lck": 20, "Def": 0, "Res": 20},
			"maxStats": {"HP": 55, "Str": 28, "Mag": 27, "Skl": 30, "Spd": 34, "Lck": 35, "Def": 27, "Res": 35},
			"weaponRanks": {"Lance": "A", "Staff": "B"},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Kinshi_Knight": {
			"key": "Kinshi_Knight",
			"name": "Kinshi Knight",
			"promotesTo": null,
			"promotesFrom": ["Sky_Knight", "Archer"],
			"classTier": "tier2",
			"skills": ["Air_Superiority", "Amaterasu"],
			"bases": {"HP": 17, "Str": 4, "Mag": 1, "Skl": 9, "Spd": 8, "Lck": 5, "Def": 4, "Res": 7},		
			"growths": {"HP": 0, "Str": 5, "Mag": 0, "Skl": 15, "Spd": 15, "Lck": 15, "Def": 0, "Res": 15},
			"maxStats": {"HP": 50, "Str": 27, "Mag": 26, "Skl": 33, "Spd": 31, "Lck": 34, "Def": 25, "Res": 31},
			"weaponRanks": {"Lance": "B", "Bow": "A"},
			"sealAccess": true,
			"inheritAccess": true,
		},
		
		"Archer": {
			"key": "Archer",
			"name": "Archer",
			"promotesTo": ["Sniper", "Kinshi_Knight"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Skill+2", "Quick_Draw"],
			"bases": {"HP": 17, "Str": 5, "Mag": 0, "Skl": 7, "Spd": 5, "Lck": 2, "Def": 4, "Res": 1},
			"growths": {"HP": 10, "Str": 15, "Mag": 0, "Skl": 15, "Spd": 15, "Lck": 5, "Def": 10, "Res": 0},
			"maxStats": {"HP": 40, "Str": 21, "Mag": 15, "Skl": 23, "Spd": 21, "Lck": 20, "Def": 20, "Res": 17},
			"weaponRanks": {"Bow": "B"},
			"parallel": "Outlaw",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Sniper": {
			"key": "Sniper",
			"name": "Sniper",
			"promotesTo": null,
			"promotesFrom": ["Archer"],
			"classTier": "tier2",
			"skills": ["Certain_Blow", "Bowfaire"],
			"bases": {"HP": 19, "Str": 7, "Mag": 0, "Skl": 10, "Spd": 9, "Lck": 3, "Def": 6, "Res": 2},		
			"growths": {"HP": 10, "Str": 15, "Mag": 0, "Skl": 20, "Spd": 15, "Lck": 5, "Def": 10, "Res": 0},
			"maxStats": {"HP": 55, "Str": 31, "Mag": 25, "Skl": 35, "Spd": 33, "Lck": 30, "Def": 31, "Res": 28},
			"weaponRanks": {"Bow": "S"},
			"bonus": {"Hit": 10, "Crit": 10},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Ninja": {
			"key": "Ninja",
			"name": "Ninja",
			"promotesTo": ["Master_Ninja", "Mechanist"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Locktouch", "Poison_Strike"],
			"bases": {"HP": 16, "Str": 3, "Mag": 0, "Skl": 8, "Spd": 8, "Lck": 1, "Def": 3, "Res": 3},
			"growths": {"HP": 5, "Str": 5, "Mag": 0, "Skl": 20, "Spd": 20, "Lck": 0, "Def": 5, "Res": 15},
			"maxStats": {"HP": 35, "Str": 17, "Mag": 15, "Skl": 25, "Spd": 25, "Lck": 18, "Def": 19, "Res": 20},
			"weaponRanks": {"Dagger": "B"},
			"parallel": "Cavalier",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Master_Ninja": {
			"key": "Master_Ninja",
			"name": "Master Ninja",
			"promotesTo": null,
			"promotesFrom": ["Ninja"],
			"classTier": "tier2",
			"skills": ["Lethality", "Shurikenfaire"],
			"bases": {"HP": 17, "Str": 5, "Mag": 0, "Skl": 10, "Spd": 11, "Lck": 2, "Def": 4, "Res": 8},
			"growths": {"HP": 5, "Str": 5, "Mag": 0, "Skl": 20, "Spd": 20, "Lck": 0, "Def": 5, "Res": 20},
			"maxStats": {"HP": 55, "Str": 27, "Mag": 25, "Skl": 35, "Spd": 35, "Lck": 28, "Def": 26, "Res": 34},
			"weaponRanks": {"Sword": "B", "Dagger": "S"},
			"bonus": {"Hit": 5, "Crit": 5, "Avo": 5, "Ddg": 5},
			"sealAccess": true,
			"inheritAccess": true,
		},	

		"Mechanist": {
			"key": "Mechanist",
			"name": "Mechanist",
			"promotesTo": null,
			"promotesFrom": ["Ninja", "Apothecary"],
			"classTier": "tier2",
			"skills": ["Golembane", "Replicate"],
			"bases": {"HP": 18, "Str": 7, "Mag": 0, "Skl": 9, "Spd": 7, "Lck": 2, "Def": 6, "Res": 6},
			"growths": {"HP": 10, "Str": 10, "Mag": 0, "Skl": 15, "Spd": 10, "Lck": 5, "Def": 5, "Res": 15},
			"maxStats": {"HP": 60, "Str": 30, "Mag": 25, "Skl": 33, "Spd": 30, "Lck": 30, "Def": 31, "Res": 31},
			"weaponRanks": {"Dagger": "A", "Bow": "B"},
			"sealAccess": true,
			"inheritAccess": true,
		},	

		"Kitsune": {
			"key": "Kitsune",
			"name": "Kitsune",
			"promotesTo": ["Nine-Tails"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Evenhanded", "Beastbane"],
			"bases": {"HP": 16, "Str": 5, "Mag": 1, "Skl": 6, "Spd": 8, "Lck": 4, "Def": 1, "Res": 4},	
			"growths": {"HP": 10, "Str": 10, "Mag": 0, "Skl": 15, "Spd": 20, "Lck": 10, "Def": 0, "Res": 20},
			"maxStats": {"HP": 40, "Str": 20, "Mag": 18, "Skl": 23, "Spd": 24, "Lck": 24, "Def": 18, "Res": 23},
			"weaponRanks": {"Stone": "B"},
			"parallel": "Apothecary",
			"sealAccess": false,
			"inheritAccess": true,
		},

		"Nine-Tails": {
			"key": "Nine-Tails",
			"name": "Nine-Tails",
			"promotesTo": null,
			"promotesFrom": ["Kitsune"],
			"classTier": "tier2",
			"skills": ["Even_Better", "Grisly_Wound"],
			"bases": {"HP": 19, "Str": 6, "Mag": 2, "Skl": 9, "Spd": 10, "Lck": 5, "Def": 2, "Res": 8},		
			"growths": {"HP": 10, "Str": 10, "Mag": 0, "Skl": 15, "Spd": 20, "Lck": 10, "Def": 0, "Res": 20},
			"maxStats": {"HP": 55, "Str": 29, "Mag": 29, "Skl": 33, "Spd": 34, "Lck": 33, "Def": 27, "Res": 34},
			"weaponRanks": {"Stone": "S"},
			"bonus": {"Crit": 5, "Avo": 10, "Ddg": 10},
			"sealAccess": false,
			"inheritAccess": true,
		},

		"Cavalier": {
			"key": "Cavalier",
			"name": "Cavalier",
			"promotesTo": ["Paladin", "Great_Knight"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Elbow_Room", "Shelter"],
			"bases": {"HP": 17, "Str": 6, "Mag": 0, "Skl": 5, "Spd": 5, "Lck": 3, "Def": 5, "Res": 3},		
			"growths": {"HP": 10, "Str": 15, "Mag": 0, "Skl": 10, "Spd": 10, "Lck": 15, "Def": 10, "Res": 5},
			"maxStats": {"HP": 40, "Str": 22, "Mag": 15, "Skl": 21, "Spd": 20, "Lck": 24, "Def": 22, "Res": 21},
			"weaponRanks": {"Sword": "B", "Lance": "B"},
			"parallel": "Ninja",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Paladin": {
			"key": "Paladin",
			"name": "Paladin",
			"promotesTo": null,
			"promotesFrom": ["Cavalier"],
			"classTier": "tier2",
			"skills": ["Defender", "Aegis"],
			"bases": {"HP": 19, "Str": 8, "Mag": 1, "Skl": 7, "Spd": 7, "Lck": 4, "Def": 7, "Res": 6},		
			"growths": {"HP": 10, "Str": 15, "Mag": 0, "Skl": 10, "Spd": 10, "Lck": 15, "Def": 10, "Res": 10},
			"maxStats": {"HP": 60, "Str": 31, "Mag": 26, "Skl": 30, "Spd": 30, "Lck": 32, "Def": 32, "Res": 32},
			"weaponRanks": {"Sword": "A", "Lance": "A"},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Great_Knight": {
			"key": "Great_Knight",
			"name": "Great Knight",
			"promotesTo": null,
			"promotesFrom": ["Cavalier", "Knight"],
			"classTier": "tier2",
			"skills": ["Luna", "Armored_Blow"],
			"bases": {"HP": 21, "Str": 10, "Mag": 0, "Skl": 6, "Spd": 6, "Lck": 3, "Def": 10, "Res": 2},		
			"growths": {"HP": 20, "Str": 20, "Mag": 0, "Skl": 10, "Spd": 5, "Lck": 5, "Def": 20, "Res": 0},
			"maxStats": {"HP": 65, "Str": 35, "Mag": 25, "Skl": 29, "Spd": 27, "Lck": 28, "Def": 37, "Res": 28},
			"weaponRanks": {"Sword": "B", "Lance": "A", "Axe": "B"},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Knight": {
			"key": "Knight",
			"name": "Knight",
			"promotesTo": ["General", "Great_Knight"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Defense+2", "Natural_Cover"],
			"bases": {"HP": 19, "Str": 8, "Mag": 0, "Skl": 5, "Spd": 3, "Lck": 3, "Def": 8, "Res": 1},		
			"growths": {"HP": 20, "Str": 20, "Mag": 0, "Skl": 15, "Spd": 5, "Lck": 10, "Def": 20, "Res": 0},
			"maxStats": {"HP": 45, "Str": 24, "Mag": 15, "Skl": 22, "Spd": 17, "Lck": 22, "Def": 26, "Res": 18},
			"weaponRanks": {"Lance": "B"},
			"parallel": "Spear_Fighter",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"General": {
			"key": "General",
			"name": "General",
			"promotesTo": null,
			"promotesFrom": ["Knight"],
			"classTier": "tier2",
			"skills": ["Wary_Fighter", "Pavise"],
			"bases": {"HP": 22, "Str": 11, "Mag": 0, "Skl": 7, "Spd": 3, "Lck": 4, "Def": 12, "Res": 3},		
			"growths": {"HP": 25, "Str": 20, "Mag": 0, "Skl": 15, "Spd": 0, "Lck": 10, "Def": 20, "Res": 5},
			"maxStats": {"HP": 70, "Str": 38, "Mag": 25, "Skl": 32, "Spd": 25, "Lck": 32, "Def": 40, "Res": 30},
			"weaponRanks": {"Lance": "A", "Axe": "B"},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Fighter": {
			"key": "Fighter",
			"name": "Fighter",
			"promotesTo": ["Berserker", "Hero"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["HP+5", "Gamble"],
			"bases": {"HP": 19, "Str": 7, "Mag": 0, "Skl": 6, "Spd": 6, "Lck": 2, "Def": 4, "Res": 1},		
			"growths": {"HP": 20, "Str": 20, "Mag": 0, "Skl": 15, "Spd": 15, "Lck": 5, "Def": 5, "Res": 0},
			"maxStats": {"HP": 45, "Str": 25, "Mag": 15, "Skl": 23, "Spd": 22, "Lck": 21, "Def": 19, "Res": 18},
			"weaponRanks": {"Axe": "B"},
			"parallel": "Oni_Savage",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Berserker": {
			"key": "Berserker",
			"name": "Berserker",
			"promotesTo": null,
			"promotesFrom": ["Fighter"],
			"classTier": "tier2",
			"skills": ["Rally_Strength", "Axefaire"],
			"bases": {"HP": 24, "Str": 12, "Mag": 0, "Skl": 8, "Spd": 9, "Lck": 0, "Def": 5, "Res": 0},		
			"growths": {"HP": 30, "Str": 25, "Mag": 0, "Skl": 15, "Spd": 15, "Lck": 0, "Def": 0, "Res": 0},
			"maxStats": {"HP": 70, "Str": 40, "Mag": 25, "Skl": 32, "Spd": 33, "Lck": 25, "Def": 27, "Res": 25},
			"weaponRanks": {"Axe": "S"},
			"bonus": {"Crit": 20, "Ddg": -5},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Mercenary": {
			"key": "Mercenary",
			"name": "Mercenary",
			"promotesTo": ["Hero", "Bow_Knight"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Good_Fortune", "Strong_Riposte"],
			"bases": {"HP": 17, "Str": 5, "Mag": 0, "Skl": 7, "Spd": 6, "Lck": 2, "Def": 5, "Res": 2},		
			"growths": {"HP": 10, "Str": 15, "Mag": 0, "Skl": 20, "Spd": 15, "Lck": 5, "Def": 10, "Res": 5},
			"maxStats": {"HP": 40, "Str": 22, "Mag": 15, "Skl": 24, "Spd": 22, "Lck": 20, "Def": 21, "Res": 19},
			"weaponRanks": {"Sword": "B"},
			"parallel": "Samurai",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Hero": {
			"key": "Hero",
			"name": "Hero",
			"promotesTo": null,
			"promotesFrom": ["Mercenary", "Fighter"],
			"classTier": "tier2",
			"skills": ["Sol", "Axebreaker"],
			"bases": {"HP": 20, "Str": 8, "Mag": 0, "Skl": 10, "Spd": 8, "Lck": 3, "Def": 7, "Res": 2},		
			"growths": {"HP": 20, "Str": 15, "Mag": 0, "Skl": 20, "Spd": 15, "Lck": 5, "Def": 10, "Res": 0},
			"maxStats": {"HP": 60, "Str": 32, "Mag": 25, "Skl": 35, "Spd": 32, "Lck": 31, "Def": 30, "Res": 27},
			"weaponRanks": {"Sword": "A", "Axe": "B"},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Bow_Knight": {
			"key": "Bow_Knight",
			"name": "Bow Knight",
			"promotesTo": null,
			"promotesFrom": ["Outlaw", "Mercenary"],
			"classTier": "tier2",
			"skills": ["Rally_Skill", "Shurikenbreaker"],
			"bases": {"HP": 18, "Str": 6, "Mag": 0, "Skl": 8, "Spd": 9, "Lck": 3, "Def": 5, "Res": 6},		
			"growths": {"HP": 10, "Str": 10, "Mag": 0, "Skl": 15, "Spd": 15, "Lck": 10, "Def": 0, "Res": 10},
			"maxStats": {"HP": 55, "Str": 29, "Mag": 25, "Skl": 32, "Spd": 33, "Lck": 30, "Def": 27, "Res": 32},
			"weaponRanks": {"Sword": "B", "Bow": "A"},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Outlaw": {
			"key": "Outlaw",
			"name": "Outlaw",
			"promotesTo": ["Adventurer", "Bow_Knight"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Locktouch", "Movement+1"],
			"bases": {"HP": 16, "Str": 3, "Mag": 1, "Skl": 4, "Spd": 8, "Lck": 1, "Def": 2, "Res": 4},		
			"growths": {"HP": 0, "Str": 10, "Mag": 5, "Skl": 10, "Spd": 20, "Lck": 0, "Def": 0, "Res": 20},
			"maxStats": {"HP": 35, "Str": 19, "Mag": 18, "Skl": 20, "Spd": 24, "Lck": 18, "Def": 17, "Res": 22},
			"weaponRanks": {"Bow": "B"},
			"parallel": "Archer",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Adventurer": {
			"key": "Adventurer",
			"name": "Adventurer",
			"promotesTo": null,
			"promotesFrom": ["Outlaw"],
			"classTier": "tier2",
			"skills": ["Lucky_Seven", "Pass"],
			"bases": {"HP": 17, "Str": 4, "Mag": 6, "Skl": 6, "Spd": 10, "Lck": 2, "Def": 3, "Res": 8},		
			"growths": {"HP": 0, "Str": 5, "Mag": 15, "Skl": 5, "Spd": 20, "Lck": 0, "Def": 0, "Res": 20},
			"maxStats": {"HP": 50, "Str": 27, "Mag": 31, "Skl": 27, "Spd": 34, "Lck": 27, "Def": 25, "Res": 34},
			"weaponRanks": {"Bow": "A", "Staff": "B"},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Wyvern_Rider": {
			"key": "Wyvern_Rider",
			"name": "Wyvern Rider",
			"promotesTo": ["Wyvern_Lord", "Malig_Knight"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Strength+2", "Lunge"],
			"bases": {"HP": 17, "Str": 6, "Mag": 0, "Skl": 5, "Spd": 4, "Lck": 2, "Def": 7, "Res": 0},		
			"growths": {"HP": 10, "Str": 15, "Mag": 5, "Skl": 10, "Spd": 10, "Lck": 5, "Def": 20, "Res": 0},
			"maxStats": {"HP": 40, "Str": 22, "Mag": 17, "Skl": 21, "Spd": 20, "Lck": 19, "Def": 24, "Res": 15},
			"weaponRanks": {"Axe": "B"},
			"parallel": "Sky_Knight",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Wyvern_Lord": {
			"key": "Wyvern_Lord",
			"name": "Wyvern Lord",
			"promotesTo": null,
			"promotesFrom": ["Wyvern_Rider"],
			"classTier": "tier2",
			"skills": ["Rally_Defense", "Swordbreaker"],
			"bases": {"HP": 19, "Str": 8, "Mag": 0, "Skl": 9, "Spd": 6, "Lck": 3, "Def": 10, "Res": 1},		
			"growths": {"HP": 10, "Str": 15, "Mag": 0, "Skl": 15, "Spd": 10, "Lck": 5, "Def": 20, "Res": 0},
			"maxStats": {"HP": 60, "Str": 33, "Mag": 25, "Skl": 33, "Spd": 29, "Lck": 28, "Def": 35, "Res": 26},
			"weaponRanks": {"Lance": "B", "Axe": "A"},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Malig_Knight": {
			"key": "Malig_Knight",
			"name": "Malig Knight",
			"promotesTo": null,
			"promotesFrom": ["Wyvern_Rider"],
			"classTier": "tier2",
			"skills": ["Savage_Blow", "Trample"],
			"bases": {"HP": 18, "Str": 7, "Mag": 6, "Skl": 6, "Spd": 5, "Lck": 0, "Def": 8, "Res": 6},		
			"growths": {"HP": 0, "Str": 15, "Mag": 15, "Skl": 10, "Spd": 5, "Lck": 0, "Def": 10, "Res": 15},
			"maxStats": {"HP": 55, "Str": 31, "Mag": 30, "Skl": 28, "Spd": 27, "Lck": 25, "Def": 31, "Res": 31},
			"weaponRanks": {"Axe": "A", "Tome": "B"},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Dark_Mage": {
			"key": "Dark_Mage",
			"name": "Dark Mage",
			"promotesTo": ["Sorcerer", "Dark_Knight"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Heartseeker", "Malefic_Aura"],
			"bases": {"HP": 16, "Str": 0, "Mag": 6, "Skl": 3, "Spd": 3, "Lck": 1, "Def": 3, "Res": 5},		
			"growths": {"HP": 0, "Str": 10, "Mag": 20, "Skl": 0, "Spd": 10, "Lck": 0, "Def": 5, "Res": 10},
			"maxStats": {"HP": 35, "Str": 19, "Mag": 24, "Skl": 16, "Spd": 19, "Lck": 18, "Def": 19, "Res": 22},
			"weaponRanks": {"Tome": "B"},
			"parallel": "Diviner",
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Sorcerer": {
			"key": "Sorcerer",
			"name": "Sorcerer",
			"promotesTo": null,
			"promotesFrom": ["Dark_Mage"],
			"classTier": "tier2",
			"skills": ["Vengeance", "Bowbreaker"],
			"bases": {"HP": 17, "Str": 0, "Mag": 9, "Skl": 4, "Spd": 6, "Lck": 1, "Def": 5, "Res": 8},		
			"growths": {"HP": 0, "Str": 0, "Mag": 25, "Skl": 0, "Spd": 10, "Lck": 0, "Def": 5, "Res": 15},
			"maxStats": {"HP": 50, "Str": 25, "Mag": 35, "Skl": 26, "Spd": 29, "Lck": 26, "Def": 29, "Res": 33},
			"weaponRanks": {"Tome": "S"},
			"bonus": {"Hit": 5, "Crit": 10, "Ddg": 5},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Dark_Knight": {
			"key": "Dark_Knight",
			"name": "Dark Knight",
			"promotesTo": null,
			"promotesFrom": ["Dark_Mage"],
			"classTier": "tier2",
			"skills": ["Seal_Magic", "Lifetaker"],
			"bases": {"HP": 19, "Str": 8, "Mag": 6, "Skl": 6, "Spd": 5, "Lck": 3, "Def": 8, "Res": 6},		
			"growths": {"HP": 15, "Str": 20, "Mag": 10, "Skl": 5, "Spd": 5, "Lck": 5, "Def": 15, "Res": 5},
			"maxStats": {"HP": 55, "Str": 32, "Mag": 31, "Skl": 28, "Spd": 27, "Lck": 31, "Def": 34, "Res": 30},
			"weaponRanks": {"Sword": "B", "Tome": "A"},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Troubadour_F": {
			"key": "Troubadour_F",
			"name": "Troubadour",
			"promotesTo": ["Strategist", "Maid"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Demoiselle", "Resistance+2"],
			"bases": {"HP": 15, "Str": 0, "Mag": 3, "Skl": 7, "Spd": 5, "Lck": 4, "Def": 1, "Res": 4},		
			"growths": {"HP": 0, "Str": 0, "Mag": 10, "Skl": 20, "Spd": 10, "Lck": 15, "Def": 0, "Res": 15},
			"maxStats": {"HP": 35, "Str": 16, "Mag": 19, "Skl": 24, "Spd": 20, "Lck": 23, "Def": 16, "Res": 21},
			"weaponRanks": {"Staff": "B"},
			"bonus": {"Ddg": 10},
			"gender": "F",
			"genderEquivalent": "Troubadour_M",
			"parallel": null,
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Troubadour_M": {
			"key": "Troubadour_M",
			"name": "Troubadour",
			"promotesTo": ["Strategist", "Butler"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Gentilhomme", "Resistance+2"],
			"bases": {"HP": 15, "Str": 0, "Mag": 3, "Skl": 7, "Spd": 5, "Lck": 4, "Def": 1, "Res": 4},		
			"growths": {"HP": 0, "Str": 0, "Mag": 10, "Skl": 20, "Spd": 10, "Lck": 15, "Def": 0, "Res": 15},
			"maxStats": {"HP": 35, "Str": 16, "Mag": 19, "Skl": 24, "Spd": 20, "Lck": 23, "Def": 16, "Res": 21},
			"weaponRanks": {"Staff": "B"},
			"bonus": {"Ddg": 10},
			"gender": "M",
			"genderEquivalent": "Troubadour_F",
			"parallel": null,
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Strategist": {
			"key": "Strategist",
			"name": "Strategist",
			"promotesTo": null,
			"promotesFrom": ["Troubadour_F", "Troubadour_M"],
			"classTier": "tier2",
			"skills": ["Rally_Resistance", "Inspiration"],
			"bases": {"HP": 16, "Str": 0, "Mag": 7, "Skl": 6, "Spd": 7, "Lck": 5, "Def": 2, "Res": 7},		
			"growths": {"HP": 0, "Str": 0, "Mag": 15, "Skl": 5, "Spd": 10, "Lck": 20, "Def": 0, "Res": 15},
			"maxStats": {"HP": 45, "Str": 25, "Mag": 33, "Skl": 28, "Spd": 31, "Lck": 33, "Def": 25, "Res": 32},
			"weaponRanks": {"Tome": "B", "Staff": "A"},
			"sealAccess": true,
			"inheritAccess": true,
		},

		"Maid": {
			"key": "Maid",
			"name": "Maid",
			"promotesTo": null,
			"promotesFrom": ["Troubadour_F"],
			"classTier": "tier2",
			"skills": ["Live_to_Serve", "Tomebreaker"],
			"bases": {"HP": 18, "Str": 4, "Mag": 5, "Skl": 9, "Spd": 8, "Lck": 4, "Def": 5, "Res": 4},		
			"growths": {"HP": 0, "Str": 10, "Mag": 10, "Skl": 15, "Spd": 15, "Lck": 10, "Def": 5, "Res": 10},
			"maxStats": {"HP": 50, "Str": 28, "Mag": 31, "Skl": 33, "Spd": 33, "Lck": 32, "Def": 29, "Res": 29},
			"weaponRanks": {"Dagger": "B", "Staff": "S"},
			"gender": "F",
			"genderEquivalent": "Butler",
			"sealAccess": true,
			"inheritAccess": true,
		},	

		"Butler": {
			"key": "Butler",
			"name": "Butler",
			"promotesTo": null,
			"promotesFrom": ["Troubadour_M"],
			"classTier": "tier2",
			"skills": ["Live_to_Serve", "Tomebreaker"],
			"bases": {"HP": 18, "Str": 4, "Mag": 5, "Skl": 9, "Spd": 8, "Lck": 4, "Def": 5, "Res": 4},		
			"growths": {"HP": 0, "Str": 10, "Mag": 10, "Skl": 15, "Spd": 15, "Lck": 10, "Def": 5, "Res": 10},
			"maxStats": {"HP": 50, "Str": 28, "Mag": 31, "Skl": 33, "Spd": 33, "Lck": 32, "Def": 29, "Res": 29},
			"weaponRanks": {"Dagger": "B", "Staff": "S"},
			"gender": "M",
			"genderEquivalent": "Maid",
			"sealAccess": true,
			"inheritAccess": true,
		},	

		"Wolfskin": {
			"key": "Wolfskin",
			"name": "Wolfskin",
			"promotesTo": ["Wolfssegner"],
			"promotesFrom": null,
			"classTier": "tier1",
			"skills": ["Odd_Shaped", "Beastbane"],
			"bases": {"HP": 19, "Str": 8, "Mag": 0, "Skl": 4, "Spd": 6, "Lck": 0, "Def": 4, "Res": 0},		
			"growths": {"HP": 20, "Str": 20, "Mag": 0, "Skl": 5, "Spd": 15, "Lck": 5, "Def": 10, "Res": 0},
			"maxStats": {"HP": 45, "Str": 24, "Mag": 15, "Skl": 18, "Spd": 22, "Lck": 17, "Def": 21, "Res": 15},
			"weaponRanks": {"Stone": "B"},
			"parallel": "Outlaw",
			"sealAccess": false,
			"inheritAccess": true,
		},

		"Wolfssegner": {
			"key": "Wolfssegner",
			"name": "Wolfssegner",
			"promotesTo": null,
			"promotesFrom": ["Wolfskin"],
			"classTier": "tier2",
			"skills": ["Better_Odds", "Grisly_Wound"],
			"bases": {"HP": 22, "Str": 11, "Mag": 0, "Skl": 6, "Spd": 7, "Lck": 1, "Def": 7, "Res": 1},		
			"growths": {"HP": 20, "Str": 20, "Mag": 0, "Skl": 5, "Spd": 15, "Lck": 5, "Def": 10, "Res": 0},
			"maxStats": {"HP": 65, "Str": 36, "Mag": 25, "Skl": 29, "Spd": 31, "Lck": 26, "Def": 32, "Res": 26},
			"weaponRanks": {"Stone": "S"},
			"bonus": {"Hit": 10, "Crit": 5, "Ddg": 10},
			"sealAccess": false,
			"inheritAccess": true,
		},

		"Songstress": {
			"key": "Songstress",
			"name": "Songstress",
			"promotesTo": null,
			"promotesFrom": null,
			"classTier": "special",
			"skills": ["Luck+4", "Inspiring_Song", "Voice_of_Peace", "Foreign_Princess"],
			"bases": {"HP": 16, "Str": 3, "Mag": 0, "Skl": 6, "Spd": 5, "Lck": 3, "Def": 2, "Res": 3},
			"growths": {"HP": 0, "Str": 10, "Mag": 0, "Skl": 20, "Spd": 20, "Lck": 20, "Def": 0, "Res": 0},
			"maxStats": {"HP": 45, "Str": 28, "Mag": 27, "Skl": 31, "Spd": 31, "Lck": 35, "Def": 27, "Res": 28},
			"weaponRanks": {"Lance": "C"},
			"gender": "F",
			"parallel": "Troubadour_F",
			"sealAccess": false,
			"inheritAccess": false,
		},

		"Dread_Fighter": {
			"key": "Dread_Fighter",
			"name": "Dread Fighter",
			"promotesTo": null,
			"promotesFrom": null,
			"classTier": "special",
			"skills": ["Even_Keel", "Iron_Will", "Clarity", "Aggressor"],
			"bases": {"HP": 19, "Str": 8, "Mag": 3, "Skl": 6, "Spd": 8, "Lck": 1, "Def": 6, "Res": 9},
			"growths": {"HP": 15, "Str": 15, "Mag": 5, "Skl": 5, "Spd": 15, "Lck": 0, "Def": 5, "Res": 20},
			"maxStats": {"HP": 55, "Str": 32, "Mag": 28, "Skl": 29, "Spd": 31, "Lck": 26, "Def": 29, "Res": 34},
			"weaponRanks": {"Sword": "A", "Axe": "B", "Dagger": "B"},
			"sealAccess": false,
			"inheritAccess": false,
		},

		"Dark_Falcon": {
			"key": "Dark_Falcon",
			"name": "Dark Falcon",
			"promotesTo": null,
			"promotesFrom": null,
			"classTier": "special",
			"skills": ["Speed+2", "Relief", "Rally_Movement", "Galeforce"],
			"bases": {"HP": 17, "Str": 4, "Mag": 7, "Skl": 5, "Spd": 9, "Lck": 4, "Def": 3, "Res": 9},
			"growths": {"HP": 0, "Str": 10, "Mag": 15, "Skl": 5, "Spd": 15, "Lck": 15, "Def": 0, "Res": 20},
			"maxStats": {"HP": 45, "Str": 27, "Mag": 32, "Skl": 28, "Spd": 33, "Lck": 32, "Def": 26, "Res": 34},
			"weaponRanks": {"Lance": "B", "Tome": "A"},
			"sealAccess": false,
			"inheritAccess": false,
		},

		"Ballistician": {
			"key": "Ballistician",
			"name": "Ballistician",
			"promotesTo": null,
			"promotesFrom": null,
			"classTier": "special",
			"skills": ["Survey", "Opportunity_Shot", "Rifled_Barrel", "Surefooted"],
			"bases": {"HP": 18, "Str": 10, "Mag": 0, "Skl": 7, "Spd": 2, "Lck": 4, "Def": 3, "Res": 1},
			"growths": {"HP": 5, "Str": 25, "Mag": 0, "Skl": 15, "Spd": 0, "Lck": 10, "Def": 5, "Res": 5},
			"maxStats": {"HP": 50, "Str": 39, "Mag": 25, "Skl": 31, "Spd": 25, "Lck": 32, "Def": 27, "Res": 26},
			"weaponRanks": {"Bow": "B"},
			"gender": "M",
			"sealAccess": false,
			"inheritAccess": false,
		},

		"Witch": {
			"key": "Witch",
			"name": "Witch",
			"promotesTo": null,
			"promotesFrom": null,
			"classTier": "special",
			"skills": ["Shadowgift", "Witchs_Brew", "Warp", "Toxic_Brew"],
			"bases": {"HP": 17, "Str": 0, "Mag": 10, "Skl": 5, "Spd": 9, "Lck": 3, "Def": 4, "Res": 5},
			"growths": {"HP": 5, "Str": 0, "Mag": 25, "Skl": 5, "Spd": 20, "Lck": 5, "Def": 0, "Res": 10},
			"maxStats": {"HP": 50, "Str": 25, "Mag": 36, "Skl": 27, "Spd": 34, "Lck": 28, "Def": 26, "Res": 29},
			"weaponRanks": {"Tome": "S"},
			"bonus": {"Crit": 10, "Avo": 10},
			"gender": "F",
			"sealAccess": false,
			"inheritAccess": false,
		},

		"Lodestar": {
			"key": "Lodestar",
			"name": "Lodestar",
			"promotesTo": null,
			"promotesFrom": null,
			"classTier": "special",
			"skills": ["Dancing_Blade", "Charm", "Dual_Guarder", "Speedtaker"],
			"bases": {"HP": 19, "Str": 7, "Mag": 0, "Skl": 10, "Spd": 9, "Lck": 7, "Def": 7, "Res": 2},
			"growths": {"HP": 15, "Str": 10, "Mag": 0, "Skl": 20, "Spd": 10, "Lck": 25, "Def": 5, "Res": 5},
			"maxStats": {"HP": 60, "Str": 29, "Mag": 26, "Skl": 35, "Spd": 33, "Lck": 40, "Def": 30, "Res": 29},
			"weaponRanks": {"Sword": "S"},
			"bonus": {"Hit": 10, "Crit": 5, "Avo": 10},
			"gender": "M",
			"sealAccess": false,
			"inheritAccess": false,
		},

		"Vanguard": {
			"key": "Vanguard",
			"name": "Vanguard",
			"promotesTo": null,
			"promotesFrom": null,
			"classTier": "special",
			"skills": ["Heavy_Blade", "Veteran_Intuition", "Aether", "Strengthtaker"],
			"bases": {"HP": 21, "Str": 10, "Mag": 0, "Skl": 6, "Spd": 7, "Lck": 3, "Def": 9, "Res": 1},
			"growths": {"HP": 20, "Str": 20, "Mag": 0, "Skl": 5, "Spd": 5, "Lck": 10, "Def": 15, "Res": 0},
			"maxStats": {"HP": 65, "Str": 36, "Mag": 25, "Skl": 29, "Spd": 30, "Lck": 30, "Def": 32, "Res": 27},
			"weaponRanks": {"Sword": "A", "Axe": "B"},
			"gender": "M",
			"sealAccess": false,
			"inheritAccess": false,
		},

		"Great_Lord": {
			"key": "Great_Lord",
			"name": "Great Lord",
			"promotesTo": null,
			"promotesFrom": null,
			"classTier": "special",
			"skills": ["Dual_Striker", "Charm", "Aether", "Awakening"],
			"bases": {"HP": 18, "Str": 8, "Mag": 1, "Skl": 8, "Spd": 9, "Lck": 5, "Def": 7, "Res": 3},
			"growths": {"HP": 15, "Str": 15, "Mag": 0, "Skl": 10, "Spd": 10, "Lck": 15, "Def": 10, "Res": 5},
			"maxStats": {"HP": 60, "Str": 30, "Mag": 25, "Skl": 32, "Spd": 34, "Lck": 35, "Def": 29, "Res": 31},
			"weaponRanks": {"Sword": "A", "Lance": "B"},
			"gender": "F",
			"sealAccess": false,
			"inheritAccess": false,
		},

		"Grandmaster": {
			"key": "Grandmaster",
			"name": "Grandmaster",
			"promotesTo": null,
			"promotesFrom": null,
			"classTier": "special",
			"skills": ["Tactical_Advice", "Solidarity", "Ignis", "Rally_Spectrum"],
			"bases": {"HP": 18, "Str": 7, "Mag": 6, "Skl": 8, "Spd": 7, "Lck": 2, "Def": 6, "Res": 8},
			"growths": {"HP": 10, "Str": 15, "Mag": 15, "Skl": 15, "Spd": 5, "Lck": 0, "Def": 5, "Res": 15},
			"maxStats": {"HP": 55, "Str": 31, "Mag": 33, "Skl": 33, "Spd": 29, "Lck": 26, "Def": 28, "Res": 33},
			"weaponRanks": {"Sword": "B", "Tome": "A"},
			"gender": "M",
			"sealAccess": false,
			"inheritAccess": false,
		}
	};


	this.AVATAR_TALENTS = {
		"M": {
			"Cavalier": "Cavalier",
			"Knight": "Knight",
			"Fighter": "Fighter",
			"Mercenary": "Mercenary",
			"Outlaw": "Outlaw",
			"Samurai": "Samurai",
			"Oni_Savage": "Oni Savage",
			"Spear_Fighter": "Lancer (Spear Fighter)",
			"Diviner": "Diviner",
			"Monk": "Monk",
			"Sky_Knight": "Sky Knight",
			"Archer": "Archer",
			"Wyvern_Rider": "Dragon (Wyvern Rider)",
			"Ninja": "Ninja",
			"Dark_Mage": "Mage (Dark Mage)",
			"Troubadour_M": "Troubadour",
			"Apothecary": "Apothecary"
		},
		"F": {
			"Cavalier": "Cavalier",
			"Knight": "Knight",
			"Fighter": "Fighter",
			"Mercenary": "Mercenary",
			"Outlaw": "Outlaw",
			"Samurai": "Samurai",
			"Oni_Savage": "Oni Savage",
			"Spear_Fighter": "Lancer (Spear Fighter)",
			"Diviner": "Diviner",
			"Shrine_Maiden": "Priestess (Shrine Maiden)",
			"Sky_Knight": "Sky Knight",
			"Archer": "Archer",
			"Wyvern_Rider": "Dragon (Wyvern Rider)",
			"Ninja": "Ninja",
			"Dark_Mage": "Mage (Dark Mage)",
			"Troubadour_F": "Troubadour",
			"Apothecary": "Apothecary"
		},
	};

	this.DLC_CLASSES = ["Dread_Fighter", "Dark_Falcon", "Ballistician", "Witch", "Lodestar", "Vanguard", "Great_Lord", "Grandmaster"];


	this.getClasses = function() {
		return angular.copy(classes);
	};

	this.getClass = function(classKey) {
		return angular.copy(classes[classKey]);
	};

	this.getClassByGender = function(classKey, gender) {
		var unitClass = classes[classKey];
		if (unitClass.gender && unitClass.gender != gender && unitClass.genderEquivalent) {
			unitClass = classes[unitClass.genderEquivalent];
		}
		return angular.copy(unitClass);
	};

	this.getParallelClass = function(classKey) {
		var parallelKey = classes[classKey].parallel;
		return angular.copy(classes[parallelKey]);
	};

	this.getParallelClassByGender = function(classKey, gender) {
		var parallelKey = classes[classKey].parallel;
		var parallelClass = classes[parallelKey];
		if (parallelClass.gender && parallelClass.gender != gender && parallelClass.genderEquivalent) {
			parallelClass = classes[parallelClass.genderEquivalent];
		}
		return angular.copy(parallelClass);
	};

	this.getPromotions = function(classKey) {
		return classes[classKey].promotesTo || [];
	};




});